# Generated by Django 4.0.3 on 2022-07-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('Pnumb', models.CharField(max_length=200)),
                ('Shipad', models.CharField(max_length=200)),
                ('Citi', models.CharField(max_length=200)),
                ('Prov', models.CharField(max_length=200)),
                ('Postal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bquant', models.IntegerField()),
                ('Pack', models.CharField(max_length=200)),
                ('Bookm', models.CharField(max_length=200)),
                ('highl', models.CharField(max_length=200)),
                ('Stick', models.CharField(max_length=200)),
                ('user_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shin.pinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Binfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mod', models.CharField(max_length=200)),
                ('user_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shin.order')),
            ],
        ),
    ]
